# Generated by Django 3.2.12 on 2022-04-07 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_tabela'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='valor',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
