# Generated by Django 3.2.12 on 2022-04-28 00:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20220427_2122'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='forma_pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.formapagamento', verbose_name='Tipo de pagamento'),
        ),
    ]
