# Generated by Django 3.2.12 on 2022-05-05 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_rotativo_forma_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalista',
            name='total',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True, verbose_name='Total'),
        ),
    ]
