# Generated by Django 3.2.12 on 2022-05-11 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_mensalista_total'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='horaAdicional',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Hora adicional'),
        ),
    ]
