# Generated by Django 3.2.12 on 2022-05-12 00:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_tabela_horaadicional'),
    ]

    operations = [
        migrations.AddField(
            model_name='tabela',
            name='moto',
            field=models.BooleanField(default=False, verbose_name='Moto'),
        ),
    ]
