# Generated by Django 3.2.12 on 2022-05-12 00:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_tabela_moto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rotativo',
            name='id_veiculo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.veiculo', verbose_name='Veiculo'),
        ),
    ]
